Alert on service creation failure
Signed-off-by: Keaty Gross <kgross@pivotal.io>

diff --git a/tasks/create-service.yml b/tasks/create-service.yml
--- a/tasks/create-service.yml
+++ b/tasks/create-service.yml
@@ -28,3 +28,10 @@ run:
       echo
       sleep 5
     done
+
+    if [ `cf services | grep 'create failed' | wc -l | sed 's/ //g'` > 0 ]; do
+      echo 'Some services failed to start'
+      cf services
+      echo
+      exit 1
+    fi
